#!/usr/bin/php
<?php
	# For full functionality, run once a day
	
	if(!isset($_SERVER['argv'][1]))
	{
		echo "Usage: ".$_SERVER['argv'][0]." [Database dir]\n";
		exit(1);
	}
	else
		$_SERVER['SUA_DB_DIR'] = $_SERVER['argv'][1];
	
	require_once('../engine/include.php');

	$ges_ress = array(0, 0, 0, 0, 0);

	# Rohstoffe aller Planeten aller Benutzer zusammenzaehlen

	$dh = opendir(DB_PLAYERS);
	while(($filename = readdir($dh)) !== false)
	{
		if(!is_file(DB_PLAYERS.'/'.$filename))
			continue;
		$username = urldecode($filename);
		$user_array = get_user_array($username);
		
		if(isset($user_array['last_active']))
			$days = ceil((time()-$user_array['last_active'])/86400);
		else
			$days = ceil((time()-$user_array['registration'])/86400);
		
		# Wenn der Spieler inaktiv ist, loeschen
		if(isset($user_array['last_active']))
		{
			if(isset($user_array['umode']) && $user_array['umode'])
			{
				if($days == 280) # 40 Wochen: Nachricht
				{
					if(isset($user_array['email']) && trim($user_array['email']) != '')
						mail($user_array['email'], "Accountinaktivit\xc3\xa4t in S-U-A", "Sie erhalten diese Nachricht, weil Sie sich seit geraumer Zeit nicht mehr in Stars Under Attack angemeldet haben. Sie haben zwei Wochen Zeit, sich anzumelden, danach wird Ihr Account einer automatischen L\xc3\xb6schung unterzogen.\n\nDas Spiel erreichen Sie unter http://s-u-a.net/ \xe2\x80\x93 Ihr Benutzername lautet ".$username, "Content-Type: text/plain;\r\n  charset=\"utf-8\"\r\nFrom: ".$EMAIL_FROM."\r\nReply-To: ".$EMAIL_FROM);
				}
				elseif($days == 294) # 42 Wochen: Loeschung
				{
					if(delete_user($username))
						echo "Deleted user `".$username."' because of inactivity.\n";
					else
						echo "Error: Couldn't delete user `".$username."'.\n";
					continue;
				}
			}
			else
			{
				if($days == 21 || $days == 34)
				{
					if(isset($user_array['email']) && trim($user_array['email']) != '')
						mail($user_array['email'], "Accountinaktivit\xc3\xa4t in S-U-A", "Sie erhalten diese Nachricht, weil Sie sich seit geraumer Zeit nicht mehr in Stars Under Attack angemeldet haben. Sie haben ".(($days == 34) ? 'einen Tag' : 'zwei Wochen')." Zeit, sich anzumelden, danach wird Ihr Account einer automatischen L\xc3\xb6schung unterzogen.\n\nDas Spiel erreichen Sie unter http://s-u-a.net/ \xe2\x80\x93 Ihr Benutzername lautet ".$username, "Content-Type: text/plain;\r\n  charset=\"utf-8\"\r\nFrom: ".$EMAIL_FROM."\r\nReply-To: ".$EMAIL_FROM);
				}
				elseif($days == 35)
				{
					if(delete_user($username))
						echo "Deleted user `".$username."' because of inactivity.\n";
					else
						echo "Error: Couldn't delete user `".$username."'.\n";
					continue;
				}
			}
		}
		elseif($days == 7)
		{
			if(isset($user_array['email']) && trim($user_array['email']) != '')
				mail($user_array['email'], "Accountinaktivit\xc3\xa4t in S-U-A", "Sie erhalten diese Nachricht, weil Sie sich seit geraumer Zeit nicht mehr in Stars Under Attack angemeldet haben. Sie haben eine Woche Zeit, sich anzumelden, danach wird Ihr Account einer automatischen L\xc3\xb6schung unterzogen.\n\nDas Spiel erreichen Sie unter http://s-u-a.net/ \xe2\x80\x93 Ihr Benutzername lautet ".$username, "Content-Type: text/plain;\r\n  charset=\"utf-8\"\r\nFrom: ".$EMAIL_FROM."\r\nReply-To: ".$EMAIL_FROM);
			else
			{
				if(delete_user($username))
					echo "Deleted user `".$username."' because of inactivity.\n";
				else
					echo "Error: Couldn't delete user `".$username."'.\n";
				continue;
			}
		}

		$planets = array_keys($user_array['planets']);
		foreach($planets as $planet)
		{
			$ges_ress[0] += $user_array['planets'][$planet]['ress'][0]/$days;
			$ges_ress[1] += $user_array['planets'][$planet]['ress'][1]/$days;
			$ges_ress[2] += $user_array['planets'][$planet]['ress'][2]/$days;
			$ges_ress[3] += $user_array['planets'][$planet]['ress'][3]/$days;
			$ges_ress[4] += $user_array['planets'][$planet]['ress'][4]/$days;
		}

		unset($username);
		unset($user_array);
	}
	closedir($dh);

	# Kurs berechnen
	$min = max($ges_ress);
	if($min != 0)
	{
		foreach($ges_ress as $val)
		{
			if($val < $min && $val != 0)
				$min = $val;
		}
	}

	if($min == 0)
		$kurs = array(1, 1, 1, 1, 1);
	else
	{
		$kurs = array();
		$kurs[0] = $ges_ress[0]/$min;
		$kurs[1] = $ges_ress[1]/$min;
		$kurs[2] = $ges_ress[2]/$min;
		$kurs[3] = $ges_ress[3]/$min;
		$kurs[4] = $ges_ress[4]/$min;

		foreach($kurs as $key=>$val)
		{
			if($val == 0)
				$kurs[$key] = 1;
		}
	}

	unset($ges_ress);

	# Kurs schreiben
	$handelskurs = preg_split("/\r\n|\r|\n/", file_get_contents(DB_HANDELSKURS));
	$handelskurs[0] = $kurs[0];
	$handelskurs[1] = $kurs[1];
	$handelskurs[2] = $kurs[2];
	$handelskurs[3] = $kurs[3];
	$handelskurs[4] = $kurs[4];

	$fh = fopen(DB_HANDELSKURS, 'w');
	flock($fh, LOCK_EX);

	fwrite($fh, implode("\n", $handelskurs));

	flock($fh, LOCK_UN);
	fclose($fh);
?>
