#!/usr/bin/php
<?php
	require_once('../engine/include.php');

	$std_kurs = array(8, 4, 2, 1, 1);
	$ges_ress = array(0, 0, 0, 0, 0);
	$ges_ress2 = array(0, 0, 0, 0,);

	# Rohstoffe aller Planeten aller Benutzer zusammenzaehlen

	$dh = opendir(DB_PLAYERS);
	while(($filename = readdir($dh)) !== false)
	{
		if(substr($filename, 0, 1) == '.')
			continue;
		$username = urldecode($filename);
		$user_array = get_user_array($username);

		$planets = array_keys($user_array['planets']);
		foreach($planets as $planet)
		{
			$ges_ress[0] += $user_array['planets'][$planet]['ress'][0];
			$ges_ress[1] += $user_array['planets'][$planet]['ress'][1];
			$ges_ress[2] += $user_array['planets'][$planet]['ress'][2];
			$ges_ress[3] += $user_array['planets'][$planet]['ress'][3];
			$ges_ress[4] += $user_array['planets'][$planet]['ress'][4];
		}

		$ges_ress2[0] += $user_array['punkte'][7];
		$ges_ress2[1] += $user_array['punkte'][8];
		$ges_ress2[2] += $user_array['punkte'][9];
		$ges_ress2[3] += $user_array['punkte'][10];

		unset($username);
		unset($user_array);
	}
	closedir($dh);

	# Kurs berechnen
	$min = max($ges_ress);
	$min2 = max($ges_ress2);
	if($min != 0)
	{
		foreach($ges_ress as $val)
		{
			if($val < $min && $val != 0)
				$min = $val;
		}
	}
	if($min2 != 0)
	{
		foreach($ges_ress2 as $val)
		{
			if($val < $min2 && $val != 0)
				$min2 = $val;
		}
	}

	if($min == 0)
		$kurs = array(1, 1, 1, 1, 1);
	else
	{
		$kurs = array();
		$kurs[0] = $ges_ress[0]/$min;
		$kurs[1] = $ges_ress[1]/$min;
		$kurs[2] = $ges_ress[2]/$min;
		$kurs[3] = $ges_ress[3]/$min;
		$kurs[4] = $ges_ress[4]/$min;

		foreach($kurs as $key=>$val)
		{
			if($val == 0)
				$kurs[$key] = 1;
		}
	}

	unset($ges_ress);

	if($min2 == 0)
		$kurs2 = array(1, 1, 1, 1, 1);
	else
	{
		$kurs2 = array();
		$kurs2[0] = $ges_ress2[0]/$min2;
		$kurs2[1] = $ges_ress2[1]/$min2;
		$kurs2[2] = $ges_ress2[2]/$min2;
		$kurs2[3] = $ges_ress2[3]/$min2;

		foreach($kurs2 as $key=>$val)
		{
			if($val == 0)
				$kurs2[$key] = 1;
		}
	}

	unset($ges_ress2);

	$kurs3 = array();
	$kurs3[0] = $kurs[0]+$kurs2[0]+$std_kurs[0];
	$kurs3[1] = $kurs[1]+$kurs2[1]+$std_kurs[1];
	$kurs3[2] = $kurs[2]+$kurs2[2]+$std_kurs[2];
	$kurs3[3] = $kurs[3]+$kurs2[3]+$std_kurs[3];
	$kurs3[4] = $kurs[4]+$kurs2[3]+$std_kurs[4];
	$min3 = min($kurs3);
	$kurs3[0] /= $min3;
	$kurs3[1] /= $min3;
	$kurs3[2] /= $min3;
	$kurs3[3] /= $min3;
	$kurs3[4] /= $min3;

	# Kurs schreiben
	$handelskurs = preg_split("/\r\n|\r|\n/", file_get_contents(DB_HANDELSKURS));
	$handelskurs[0] = $kurs3[0];
	$handelskurs[1] = $kurs3[1];
	$handelskurs[2] = $kurs3[2];
	$handelskurs[3] = $kurs3[3];
	$handelskurs[4] = $kurs3[4];

	$fh = fopen(DB_HANDELSKURS, 'w');
	flock($fh, LOCK_EX);

	fwrite($fh, implode("\n", $handelskurs));

	flock($fh, LOCK_UN);
	fclose($fh);
?>