#!/usr/bin/php
This program is free software; you can redistribute it and/or modify it under the terms of the AFFERO GENERAL PUBLIC LICENSE as published by Affero Inc.; either version 1 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the AFFERO GENERAL PUBLIC LICENSE for more details.
You should have received a copy of the AFFERO GENERAL PUBLIC LICENSE along with this program; if not, write to Affero Inc., 510 Third Street - Suite 225, San Francisco, CA 94107, USA or have a look at http://www.affero.org/oagpl.html.

<?php
	$USE_OB = false;
	require('../engine/include.php');

	if(!isset($_SERVER['argv'][1]))
	{
		fputs(STDERR, "Usage: ".$_SERVER['argv'][0]." <Database ID>\n");
		exit(1);
	}
	else
	{
		$databases = get_databases();
		if(!define_globals($_SERVER['argv'][1]))
		{
			fputs(STDERR, "Unknown database.\n");
			exit(1);
		}
	}

	__autoload("Fleet");
	$fd = new FleetDatabase();
	$fd->query("SELECT fleet_id FROM fleets");
	while($r = $fd->nextResult())
	{
		$fleet = Classes::Fleet($r["fleet_id"]);
		if($fleet->getStatus() != 1)
			fputs(STDERR, "Error: Could not not process fleet ".$fleet->getName().".\n");
		$callback = false;
		foreach($fleet->getTargetsInformation() as $i)
		{
			if($i[0] == 3 && !$i[1])
			{
				$callback = true;
				break;
			}
		}

		if($callback)
		{
			foreach($fleet->getUsersList() as $user)
			{
				if(!$fleet->callBack($user, true))
					fputs(STDERR, "Error: Could not call back user ".$user." in fleet ".$fleet->getName().".\n");
			}
		}
	}
?>
