#!/usr/bin/php
    This file is part of Stars Under Attack.

    Stars Under Attack is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Stars Under Attack is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with Stars Under Attack.  If not, see <http://www.gnu.org/licenses/>.

<?php
	chdir(dirname(__FILE__));
	$USE_OB = false;
	require('../engine/include.php');

	if(!isset($_SERVER['argv'][1]))
	{
		fputs(STDERR, "Usage: ".$_SERVER['argv'][0]." <Database ID>\n");
		exit(1);
	}
	else
	{
		$databases = get_databases();
		if(!define_globals($_SERVER['argv'][1]))
		{
			fputs(STDERR, "Unknown database.\n");
			exit(1);
		}
	}

	__autoload("Fleet");
	$fd = new FleetDatabase();
	$fd->query("SELECT fleet_id FROM fleets");
	while($r = $fd->nextResult())
	{
		$fleet = Classes::Fleet($r["fleet_id"]);
		if($fleet->getStatus() != 1)
			fputs(STDERR, "Error: Could not not process fleet ".$fleet->getName().".\n");
		$callback = false;
		foreach($fleet->getTargetsInformation() as $i)
		{
			if($i[0] == 3 && !$i[1])
			{
				$callback = true;
				break;
			}
		}

		if($callback)
		{
			foreach($fleet->getUsersList() as $user)
			{
				if(!$fleet->callBack($user, true))
					fputs(STDERR, "Error: Could not call back user ".$user." in fleet ".$fleet->getName().".\n");
			}
		}
	}
?>
