#!/bin/bash
cat <<EOF
    This file is part of Stars Under Attack.

    Stars Under Attack is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Stars Under Attack is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with Stars Under Attack.  If not, see <http://www.gnu.org/licenses/>.

EOF

if [ $# -lt 1 ]
then
	echo "Usage: $0 <filename>"
	exit 1
fi

BINDIR="$(dirname $0)"

mkdir $1 || exit 1

echo '9' > $1/.version
touch $1/locked
echo 'Order Deny,Allow' > $1/.htaccess
echo 'Deny from All' >> $1/.htaccess
echo 'Allow from None' >> $1/.htaccess
mkdir $1/alliances
mkdir $1/items
ln -s $PWD/gebaeude $1/items/gebaeude
ln -s $PWD/forschung $1/items/forschung
ln -s $PWD/roboter $1/items/roboter
ln -s $PWD/schiffe $1/items/schiffe
ln -s $PWD/verteidigung $1/items/verteidigung
mkdir $1/players
mkdir $1/truemmerfelder
mkdir $1/universe
ln -s $CWD/create_galaxy $1/universe/create_galaxy
touch $1/admins
read -p "Enter Admin user name: " ADMIN_USERNAME
read -s -p "Enter Admin password: " ADMIN_PASSWD
echo

echo -n "$ADMIN_USERNAME" > $1/admins
echo -ne "\t" >> $1/admins
echo -n "$ADMIN_PASSWD" | md5sum | awk '{ ORS=""; print $1; }' >> $1/admins
echo -ne "\t1\t1\t1\t1\t1\t1\t1\t1\t1\t1\t1\t1\t1\t1\t1\t1" >> $1/admins

unset ADMIN_PASSWD

$BINDIR/create_galaxy "$1/universe/1"

chmod -R a+rw $1

exit 0
