#!/usr/bin/php
This program is free software; you can redistribute it and/or modify it under the terms of the AFFERO GENERAL PUBLIC LICENSE as published by Affero Inc.; either version 1 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the AFFERO GENERAL PUBLIC LICENSE for more details.
You should have received a copy of the AFFERO GENERAL PUBLIC LICENSE along with this program; if not, write to Affero Inc., 510 Third Street - Suite 225, San Francisco, CA 94107, USA or have a look at http://www.affero.org/oagpl.html.

<?php
	chdir(dirname(__FILE__));
	$USE_OB = false;
	require('../engine/include.php');

	if(!isset($_SERVER['argv'][1]))
	{
		fputs(STDERR, "Usage: ".$_SERVER['argv'][0]." <Database ID>\n");
		exit(1);
	}
	else
	{
		$databases = get_databases();
		if(!define_globals($_SERVER['argv'][1]))
		{
			fputs(STDERR, "Unknown database.\n");
			exit(1);
		}
	}

	$dh = opendir(global_setting("DB_PLAYERS"));
	while(($fname = readdir($dh)) !== false)
	{
		$path = global_setting("DB_PLAYERS")."/".$fname;
		if(!is_file($path)) continue;

		$user = new User(urldecode($fname));
		foreach($user->getVerbuendetList() as $verb)
		{
			$verb_obj = new User($verb);
			if(!$verb_obj->isVerbuendet($user->getName()))
			{
				$user->_removeVerbuendet($verb);
				fputs(STDOUT, $user->getName().": ".$verb." isn't Verbuendet anymore.\n");
			}
			unset($verb_obj);
		}
		unset($user);
	}
	closedir($dh);

	exit(0);
?>
