#!/usr/bin/php
This program is free software; you can redistribute it and/or modify it under the terms of the AFFERO GENERAL PUBLIC LICENSE as published by Affero Inc.; either version 1 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the AFFERO GENERAL PUBLIC LICENSE for more details.
You should have received a copy of the AFFERO GENERAL PUBLIC LICENSE along with this program; if not, write to Affero Inc., 510 Third Street - Suite 225, San Francisco, CA 94107, USA or have a look at http://www.affero.org/oagpl.html.

<?php
	chdir(dirname(__FILE__));
	$USE_OB = false;
	require('../engine/include.php');

	if(!isset($_SERVER['argv'][1]))
	{
		echo "Usage: ".$_SERVER['argv'][0]." <Database ID>\n";
		exit(1);
	}
	else
	{
		$databases = get_databases();
		if(!define_globals($_SERVER['argv'][1]))
		{
			echo "Unknown database.\n";
			exit(1);
		}
	}

	function check_number($no)
	{
		return preg_match("/^[1-9]([0-9]*)$/", $no);
	}

	$d = global_setting("DB_PLAYERS")."/";
	$dh = opendir($d);
	while(($fname = readdir($dh)) !== false)
	{
		$player = urldecode($fname);
		$fname = $d.$fname;
		if(!is_file($fname) || !is_readable($fname)) continue;

		$arr = unserialize(bzdecompress(file_get_contents($fname)));
		foreach(array_keys($arr['planets']) as $p)
		{
			$pos = explode(":", $arr['planets'][$p]['pos']);
			$correct = 1;
			if(count($pos) != 3) $correct = 0;
			elseif(!check_number($pos[0]) || !check_number($pos[1]) || !check_number($pos[2]))
			{
				$correct = 0;
				$pos[0] = preg_replace("/^0+/", "", trim($pos[0]));
				$pos[1] = preg_replace("/^0+/", "", trim($pos[1]));
				$pos[2] = preg_replace("/^0+/", "", trim($pos[2]));
				if(check_number($pos[0]) && check_number($pos[1]) && check_number($pos[2]))
					$correct = 2;
			}

			if($correct != 1)
				echo "Invalid coordinates ".$arr['planets'][$p]['pos']." (player ".$player.", planet ".$p.")\n";
			if($correct == 2)
			{
				$arr['planets'][$p]['pos'] = implode(":", $pos);
				if(file_put_contents($fname, bzcompress(serialize($arr))))
					echo "Corrected to: ".$arr['planets'][$p]['pos']."\n";
				else
					echo "Could not fix: writing failed.\n";
			}
		}
	}
	closedir($dh);
?>
