#!/usr/bin/php
    This file is part of Stars Under Attack.

    Stars Under Attack is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Stars Under Attack is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with Stars Under Attack.  If not, see <http://www.gnu.org/licenses/>.

<?php
	if(!isset($_SERVER['argv'][1]))
	{
		echo "Usage: ".$_SERVER['argv'][0]." [Events file]\n";
		exit(1);
	}

	$conn = sqlite_popen($_SERVER['argv'][1]);
	var_dump(sqlite_array_query($conn, "SELECT * FROM events", SQLITE_ASSOC));
	sqlite_close($conn);
?>
