#!/usr/bin/php
This program is free software; you can redistribute it and/or modify it under the terms of the AFFERO GENERAL PUBLIC LICENSE as published by Affero Inc.; either version 1 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the AFFERO GENERAL PUBLIC LICENSE for more details.
You should have received a copy of the AFFERO GENERAL PUBLIC LICENSE along with this program; if not, write to Affero Inc., 510 Third Street - Suite 225, San Francisco, CA 94107, USA or have a look at http://www.affero.org/oagpl.html.

<?php
	$USE_OB = false;
	require('../engine/include.php');

	if(!isset($_SERVER['argv'][1]))
	{
		echo "Usage: ".$_SERVER['argv'][0]." <Database ID>\n";
		exit(1);
	}
	else
	{
		$databases = get_databases();
		if(!define_globals($_SERVER['argv'][1]))
		{
			echo "Unknown database.\n";
			exit(1);
		}
	}

	$eventfile = Classes::EventFile();
	$eventfile->_empty();

	__autoload("Fleet");
	$fd = new FleetDatabase();
	$fd->query("SELECT fleet_id FROM fleets");
	while($r = $fd->nextResult())
	{
		$fleet_id = $r['fleet_id'];
		$fleet = new Fleet($fleet_id);
		if(!$fleet->getStatus()) continue;

		$eventfile->addNewFleet($fleet->getNextArrival(), $fleet_id);
		unset($fleet);
	}
?>
