#!/usr/bin/php
    This file is part of Stars Under Attack.

    Stars Under Attack is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Stars Under Attack is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with Stars Under Attack.  If not, see <http://www.gnu.org/licenses/>.

<?php
	chdir(dirname(__FILE__));
	$USE_OB = false;
	require('../engine/include.php');

	if(!isset($_SERVER['argv'][1]))
	{
		fputs(STDERR, "Usage: ".$_SERVER['argv'][0]." <Database ID>\n");
		exit(1);
	}
	else
	{
		$databases = get_databases();
		if(!define_globals($_SERVER['argv'][1]))
		{
			fputs(STDERR, "Unknown database.\n");
			exit(1);
		}
	}

	// Reset all planets
	__autoload("Galaxy");
	for($galaxy = 1; $galaxy <= getGalaxiesCount(); $galaxy++)
	{
		$g_obj = Classes::Galaxy($galaxy);
		for($system = 1; $system <= $g_obj->getSystemsCount(); $system++)
		{
			for($planet = 1; $planet <= $g_obj->getPlanetsCount($system); $planet++)
			{
				$g_obj->_setPlanetOwner($system, $planet, "");
				$g_obj->setPlanetName($system, $planet, "");
				$g_obj->setPlanetOwnerAlliance($system, $planet, "");
			}
		}
	}

	$dh = opendir(global_setting("DB_PLAYERS"));
	while(($fname = readdir($dh)) !== false)
	{
		if($fname == '.' || $fname == '..') continue;

		$user_obj = new User(urldecode($fname));
		if(!$user_obj->getStatus())
		{
			fputs(STDERR, "Error processing user ".$user_obj->getName().".\n");
			unset($user_obj);
			continue;
		}

		foreach($user_obj->getPlanetsList() as $planet_idx)
		{
			$user_obj->setActivePlanet($planet_idx);
			$planet = $user_obj->getPos();
			$galaxy_obj = Classes::Galaxy($planet[0]);
			$galaxy_obj->setPlanetOwner($planet[1], $planet[2], $user_obj->getName());
			if($user_obj->userLocked()) $galaxy_obj->setPlanetOwnerFlag($planet[1], $planet[2], "g");
			elseif($user_obj->umode()) $galaxy_obj->setPlanetOwnerFlag($planet[1], $planet[2], "U");
			$galaxy_obj->setPlanetName($planet[1], $planet[2], $user_obj->planetName());
			if($user_obj->allianceTag())
				$galaxy_obj->setPlanetOwnerAlliance($planet[1], $planet[2], $user_obj->allianceTag());
		}
		unset($user_obj);
	}
	closedir($dh);
	exit(0);
?>
