#!/usr/bin/php
<?php
	$USE_OB = false;
	require('../engine/include.php');

	if(!isset($_SERVER['argv'][1]))
	{
		echo "Usage: ".$_SERVER['argv'][0]." <Database ID>\n";
		exit(1);
	}
	else
	{
		$databases = get_databases();
		if(!define_globals($_SERVER['argv'][1]))
		{
			echo "Unknown database.\n";
			exit(1);
		}
	}

	$eventfile = Classes::EventFile();
	$eventfile->_empty();

	__autoload("Fleet");
	$fd = new FleetDatabase();
	$fd->query("SELECT fleet_id FROM fleets");
	while($r = $fd->nextResult())
	{
		$fleet_id = $r['fleet_id'];
		$fleet = new Fleet($fleet_id);
		if(!$fleet->getStatus()) continue;

		$eventfile->addNewFleet($fleet->getNextArrival(), $fleet_id);
		unset($fleet);
	}
?>
