#!/usr/bin/php
<?php
	if(!isset($_SERVER['argv'][1]))
	{
		echo "Usage: ".$_SERVER['argv'][0]." [Database dir]\n";
		exit(1);
	}
	else
		$_SERVER['SUA_DB_DIR'] = $_SERVER['argv'][1];
	
	require('../engine/include.php');

	function sort_highscores($a, $b)
	{
		if($a[0] < $b[0])
			return 1;
		elseif($a[0] > $b[0])
			return -1;
		else
			return 0;
	}

	lock_database();

	$highscores = array();

	$dh = opendir(DB_PLAYERS);
	while(($fname = readdir($dh)) !== false)
	{
		if(!is_file(DB_PLAYERS.'/'.$fname) || !is_readable(DB_PLAYERS.'/'.$fname))
			continue;

		$this_user_array = get_user_array(urldecode($fname));

		if($this_user_array === false)
			continue;

		$new_points = floor($this_user_array['punkte'][0]+$this_user_array['punkte'][1]+$this_user_array['punkte'][2]+$this_user_array['punkte'][3]+$this_user_array['punkte'][4]+$this_user_array['punkte'][5]+$this_user_array['punkte'][6]);

		if(!isset($this_user_array['alliance']))
			$this_user_array['alliance'] = '';
		$highscores[urldecode($fname)] = array($new_points, $this_user_array['alliance']);
		
		unset($this_user_array);
	}
	closedir($dh);

	uasort($highscores, 'sort_highscores');

	$platz = 1;
	$fh = fopen(DB_HIGHSCORES, 'w');
	foreach($highscores as $player=>$punkte)
	{
		fwrite($fh, highscores::make_info($player, $punkte[0], $punkte[1]));

		$this_user_array = get_user_array($player);
		$this_user_array['punkte'][12] = $platz;
		write_user_array($player, $this_user_array);
		unset($this_user_array);

		$platz++;
	}
	fclose($fh);
	
	$alliance_highscores = array();
	$dh = opendir(DB_ALLIANCES);
	while(($fname = readdir($dh)) !== false)
	{
		if(!is_file(DB_ALLIANCES.'/'.$fname) || !is_readable(DB_ALLIANCES.'/'.$fname))
			continue;

		$this_alliance_array = get_alliance_array(urldecode($fname));

		if($this_alliance_array === false)
			continue;

		$new_points = 0;
		foreach($this_alliance_array['members'] as $member)
			$new_points += $member['punkte'];
		$new_points = floor($new_points/count($this_alliance_array['members']));
		
		unset($this_alliance_array);
		
		$alliance_highscores[urldecode($fname)] = $new_points;
	}
	closedir($dh);
	
	arsort($alliance_highscores, SORT_NUMERIC);
	
	$platz = 1;
	$fh = fopen(DB_HIGHSCORES_ALLIANCES, 'w');
	foreach($alliance_highscores as $alliance=>$punkte)
	{
		fwrite($fh, highscores_alliances::make_info($alliance, $punkte));

		$this_alliance_array = get_alliance_array($alliance);
		$this_alliance_array['platz'] = $platz;
		write_alliance_array($alliance, $this_alliance_array);
		unset($this_alliance_array);

		$platz++;
	}
	fclose($fh);

	unlock_database();
?>