#!/usr/bin/php
This program is free software; you can redistribute it and/or modify it under the terms of the AFFERO GENERAL PUBLIC LICENSE as published by Affero Inc.; either version 1 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the AFFERO GENERAL PUBLIC LICENSE for more details.
You should have received a copy of the AFFERO GENERAL PUBLIC LICENSE along with this program; if not, write to Affero Inc., 510 Third Street - Suite 225, San Francisco, CA 94107, USA or have a look at http://www.affero.org/oagpl.html.

<?php
	$USE_OB = false;
	require('../engine/include.php');

	if(!isset($_SERVER['argv'][1]))
	{
		echo "Usage: ".$_SERVER['argv'][0]." <Database ID>\n";
		exit(1);
	}
	else
	{
		$databases = get_databases();
		if(!define_globals($_SERVER['argv'][1]))
		{
			echo "Unknown database.\n";
			exit(1);
		}
	}

	$highscores_obj = Classes::Highscores();
	$highscores_obj->destroy();

	$dh = opendir(global_setting("DB_PLAYERS"));
	while(($fname = readdir($dh)) !== false)
	{
		if(!is_file(global_setting("DB_PLAYERS").'/'.$fname) || !is_readable(global_setting("DB_PLAYERS").'/'.$fname))
			continue;

		# Not using instances for memory reasons
		$this_user = new User(urldecode($fname));
		if(!$this_user->getStatus()) continue;

		//$highscores_obj->updateUser($this_user->getName(), $this_user->allianceTag(), $this_user->getScores());
		$this_user->doRecalcHighscores();

		unset($this_user);
	}
	closedir($dh);

	$dh = opendir(global_setting("DB_ALLIANCES"));
	while(($fname = readdir($dh)) !== false)
	{
		if(!is_file(global_setting("DB_ALLIANCES").'/'.$fname) || !is_readable(global_setting("DB_ALLIANCES").'/'.$fname))
			continue;

		$this_alliance = new Alliance(urldecode($fname));
		if(!$this_alliance->getStatus())
			continue;

		$overall = $this_alliance->getTotalScores();
		$members = $this_alliance->getMembersCount();
		$average = floor($overall/$members);

		$highscores_obj->updateAlliance($this_alliance->getName(), $average, $overall, $members);

		unset($this_alliance);
	}
	closedir($dh);

	exit(0);
?>
