#!/usr/bin/php
This program is free software; you can redistribute it and/or modify it under the terms of the AFFERO GENERAL PUBLIC LICENSE as published by Affero Inc.; either version 1 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the AFFERO GENERAL PUBLIC LICENSE for more details.
You should have received a copy of the AFFERO GENERAL PUBLIC LICENSE along with this program; if not, write to Affero Inc., 510 Third Street - Suite 225, San Francisco, CA 94107, USA or have a look at http://www.affero.org/oagpl.html.

<?php
	chdir(dirname(__FILE__));
	$USE_OB = false;
	require('../engine/include.php');

	if(!isset($_SERVER['argv'][1]))
	{
		fputs(STDERR, "Usage: ".$_SERVER['argv'][0]." <Database ID>\n");
		exit(1);
	}
	else
	{
		$databases = get_databases();
		if(!define_globals($_SERVER['argv'][1]))
		{
			fputs(STDERR, "Unknown database.\n");
			exit(1);
		}
	}

	// Reset all planets
	__autoload("Galaxy");
	for($galaxy = 1; $galaxy <= getGalaxiesCount(); $galaxy++)
	{
		$g_obj = Classes::Galaxy($galaxy);
		for($system = 1; $system <= $g_obj->getSystemsCount(); $system++)
		{
			for($planet = 1; $planet <= $g_obj->getPlanetsCount($system); $planet++)
				$g_obj->setPlanetOwner($system, $planet, "");
		}
	}

	$dh = opendir(global_setting("DB_PLAYERS"));
	while(($fname = readdir($dh)) !== false)
	{
		if($fname == '.' || $fname == '..') continue;

		$user_obj = new User(urldecode($fname));
		if(!$user_obj->getStatus())
		{
			fputs(STDERR, "Error processing user ".$user_obj->getName().".\n");
			unset($user_obj);
			continue;
		}

		foreach($user_obj->getPlanetsList() as $planet_idx)
		{
			$user_obj->setActivePlanet($planet_idx);
			$planet = $user_obj->getPos();
			$galaxy_obj = Classes::Galaxy($planet[0]);
			$galaxy_obj->setPlanetOwner($planet[1], $planet[2], $user_obj->getName());
		}
		unset($user_obj);
	}
	closedir($dh);
	exit(0);
?>
