#!/usr/bin/php
<?php
	$USE_OB = false;
	require('../engine/include.php');

	if(!isset($_SERVER['argv'][1]))
	{
		fputs(STDERR, "Usage: ".$_SERVER['argv'][0]." <Database ID>\n");
		exit(1);
	}
	else
	{
		$databases = get_databases();
		if(!define_globals($_SERVER['argv'][1]))
		{
			fputs(STDERR, "Unknown database.\n");
			exit(1);
		}
	}

	// Reset all planets
	__autoload("Galaxy");
	for($galaxy = 1; $galaxy <= getGalaxiesCount(); $galaxy++)
	{
		$g_obj = Classes::Galaxy($galaxy);
		for($system = 1; $system <= $g_obj->getSystemsCount(); $system++)
		{
			for($planet = 1; $planet <= $g_obj->getPlanetsCount($system); $planet++)
				$g_obj->setPlanetOwner($system, $planet, "");
		}
	}

	$dh = opendir(global_setting("DB_PLAYERS"));
	while(($fname = readdir($dh)) !== false)
	{
		if($fname == '.' || $fname == '..') continue;

		$user_obj = new User(urldecode($fname));
		if(!$user_obj->getStatus())
		{
			fputs(STDERR, "Error processing user ".$user_obj->getName().".\n");
			unset($user_obj);
			continue;
		}

		foreach($user_obj->getPlanetsList() as $planet_idx)
		{
			$user_obj->setActivePlanet($planet_idx);
			$planet = $user_obj->getPos();
			$galaxy_obj = Classes::Galaxy($planet[0]);
			$galaxy_obj->setPlanetOwner($planet[1], $planet[2], $user_obj->getName());
		}
		unset($user_obj);
	}
	closedir($dh);
	exit(0);
?>
