#!/usr/bin/php
This program is free software; you can redistribute it and/or modify it under the terms of the AFFERO GENERAL PUBLIC LICENSE as published by Affero Inc.; either version 1 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the AFFERO GENERAL PUBLIC LICENSE for more details.
You should have received a copy of the AFFERO GENERAL PUBLIC LICENSE along with this program; if not, write to Affero Inc., 510 Third Street - Suite 225, San Francisco, CA 94107, USA or have a look at http://www.affero.org/oagpl.html.

<?php
	chdir(dirname(__FILE__));
	$USE_OB = false;
	require('../engine/include.php');

	if(!isset($_SERVER['argv'][1]))
	{
		echo "Usage: ".$_SERVER['argv'][0]." <Database ID>\n";
		exit(1);
	}
	else
	{
		$databases = get_databases();
		if(!define_globals($_SERVER['argv'][1]))
		{
			echo "Unknown database.\n";
			exit(1);
		}
	}

	$d = global_setting("DB_PLAYERS")."/";
	$dh = opendir($d);
	while(($fname = readdir($dh)) !== false)
	{
		$changed = false;
		$fname = $d.$fname;
		if(!is_file($fname) || !is_readable($fname)) continue;

		$arr = unserialize(bzdecompress(file_get_contents($fname)));
		foreach(array_keys($arr["planets"]) as $p)
			$arr["planets"][$p]["foreign_fleets"] = array();
		$arr["foreign_fleets"] = array();
		if(!file_put_contents($fname, bzcompress(serialize($arr))))
			echo "Could not fix ".$fname.": writing failed.\n";
	}
	closedir($dh);
?>
