#!/usr/bin/php
<?php
	require_once('../engine/include.php');
	
	if(!isset($_SERVER['argv'][1]))
	{
		echo "Usage: ".$_SERVER['argv'][0]." [Database dir]\n";
		exit(1);
	}
	else
		define_globals($_SERVER['argv'][1]);

	$ges_ress = array(0, 0, 0, 0, 0);

	# Rohstoffe aller Planeten aller Benutzer zusammenzaehlen

	$dh = opendir(DB_PLAYERS);
	while(($filename = readdir($dh)) !== false)
	{
		if(!is_file(DB_PLAYERS.'/'.$filename))
			continue;
		
		# Not using instances for memory reasons
		$user = new User(urldecode($filename));
		if(!$user->getStatus()) return false;
		
		$last_activity = $user->getLastActivity();
		if($last_activity !== false)
			$days = ceil((time()-$last_activity)/86400);
		else
			$days = ceil((time()-$user->getRegistrationTime())/86400);
		
		$today = date('Y-m-d');
		
		# Wenn der Spieler inaktiv ist, loeschen
		if($last_activity !== false)
		{
			if($user->umode())
			{
				if($days == 175 && $user->lastMailSent() != $today) # 25 Wochen: Nachricht
				{
					if($user->checkSetting('email'))
					{
						mail($user->checkSetting('email'), "Accountinaktivit\xc3\xa4t in S-U-A", "Sie erhalten diese Nachricht, weil Sie sich seit geraumer Zeit nicht mehr in Stars Under Attack angemeldet haben. Sie haben zwei Wochen Zeit, sich anzumelden, danach wird Ihr Account einer automatischen L\xc3\xb6schung unterzogen.\n\nDas Spiel erreichen Sie unter http://s-u-a.net/ \xe2\x80\x93 Ihr Benutzername lautet ".$username, "Content-Type: text/plain;\r\n  charset=\"utf-8\"\r\nFrom: ".EMAIL_FROM."\r\nReply-To: ".EMAIL_FROM);
						$user->lastMailSent($today);
					}
				}
				elseif($days >= 189) # 27 Wochen: Loeschung
				{
					if($user->destroy())
						echo "Deleted user `".$user->getName()."' because of inactivity.\n";
					else
						echo "Error: Couldn't delete user `".$user->getName()."'.\n";
					continue;
				}
			}
			else
			{
				if(($days == 21 || $days == 34) && $user->lastMailSent() != $today)
				{
					if($user->checkSetting('email'))
					{
						mail($user->checkSetting('email'), "Accountinaktivit\xc3\xa4t in S-U-A", "Sie erhalten diese Nachricht, weil Sie sich seit geraumer Zeit nicht mehr in Stars Under Attack angemeldet haben. Sie haben ".(($days == 34) ? 'einen Tag' : 'zwei Wochen')." Zeit, sich anzumelden, danach wird Ihr Account einer automatischen L\xc3\xb6schung unterzogen.\n\nDas Spiel erreichen Sie unter http://s-u-a.net/ \xe2\x80\x93 Ihr Benutzername lautet ".$username, "Content-Type: text/plain;\r\n  charset=\"utf-8\"\r\nFrom: ".EMAIL_FROM."\r\nReply-To: ".EMAIL_FROM);
						$user->lastMailSent($today);
					}
				}
				elseif($days >= 35)
				{
					if($user->destroy())
						echo "Deleted user `".$user->getName()."' because of inactivity.\n";
					else
						echo "Error: Couldn't delete user `".$user->getName()."'.\n";
					continue;
				}
			}
		}
		elseif($days == 7 && $user->lastMailSent() != $today)
		{
			if($user->checkSetting('email'))
				mail($user->checkSetting('email'), "Accountinaktivit\xc3\xa4t in S-U-A", "Sie erhalten diese Nachricht, weil Sie sich seit geraumer Zeit nicht mehr in Stars Under Attack angemeldet haben. Sie haben eine Woche Zeit, sich anzumelden, danach wird Ihr Account einer automatischen L\xc3\xb6schung unterzogen.\n\nDas Spiel erreichen Sie unter http://s-u-a.net/ \xe2\x80\x93 Ihr Benutzername lautet ".$username, "Content-Type: text/plain;\r\n  charset=\"utf-8\"\r\nFrom: ".EMAIL_FROM."\r\nReply-To: ".EMAIL_FROM);
		}
		elseif($days >= 14)
		{
			if($user->destroy())
				echo "Deleted user `".$user->getName()."' because of inactivity.\n";
			else
				echo "Error: Couldn't delete user `".$user->getName()."'.\n";
			continue;
		}

		$planets = $user->getPlanetsList();
		foreach($planets as $planet)
		{
			$user->setActivePlanet($planet);
			$ress = $user->getRess();
			$min = max($ress);
			if($min != 0)
			{
				foreach($ress as $val)
				{
					if($val < $min && $val != 0) $min = $val;
				}
				
				$ress[0] /= $min;
				$ress[1] /= $min;
				$ress[2] /= $min;
				$ress[3] /= $min;
				$ress[4] /= $min;
			}
			
			$ress[0] = pow($ress[0], 1/($days+1));
			$ress[1] = pow($ress[1], 1/($days+1));
			$ress[2] = pow($ress[2], 1/($days+1));
			$ress[3] = pow($ress[3], 1/($days+1));
			$ress[4] = pow($ress[4], 1/($days+1));
			
			$ges_ress[0] += $ress[0];
			$ges_ress[1] += $ress[1];
			$ges_ress[2] += $ress[2];
			$ges_ress[3] += $ress[3];
			$ges_ress[4] += $ress[4];
		}
		unset($user);
	}
	closedir($dh);

	# Kurs berechnen
	$min = max($ges_ress);
	if($min != 0)
	{
		foreach($ges_ress as $val)
		{
			if($val < $min && $val != 0)
				$min = $val;
		}
	}

	if($min == 0)
		$kurs = array(10, 5, 3.75, 2.5, 1);
	else
	{
		$kurs = array();
		$kurs[0] = $ges_ress[0]/$min;
		$kurs[1] = $ges_ress[1]/$min;
		$kurs[2] = $ges_ress[2]/$min;
		$kurs[3] = $ges_ress[3]/$min;
		$kurs[4] = $ges_ress[4]/$min;

		foreach($kurs as $key=>$val)
		{
			if($val == 0)
				$kurs[$key] = 1;
		}
	}

	unset($ges_ress);

	# Kurs schreiben
	$handelskurs = preg_split("/\r\n|\r|\n/", file_get_contents(DB_HANDELSKURS));
	$handelskurs[0] = $kurs[0];
	$handelskurs[1] = $kurs[1];
	$handelskurs[2] = $kurs[2];
	$handelskurs[3] = $kurs[3];
	$handelskurs[4] = $kurs[4];

	$fh = fopen(DB_HANDELSKURS, 'w');
	flock($fh, LOCK_EX);

	fwrite($fh, implode("\n", $handelskurs));

	flock($fh, LOCK_UN);
	fclose($fh);
?>