#!/bin/bash
cd "$(dirname "$(which "$0")")"
echo '<?php' > refresh_tmp.php
( cat ../database.global/{gebaeude,forschung,roboter,schiffe,verteidigung} | cut -f 1 | xargs -n1 -I{} echo -e 'item_{}\nitemdesc_{}' ; cat << EOF ) | xargs -n1 -I{} echo '_("[{}]");' >> refresh_tmp.php
message_1
message_2
message_3
message_4
message_5
message_6
message_7
message_8
fleet_1
fleet_2
fleet_3
fleet_4
fleet_5
fleet_6
EOF
find .. -name '*.php' | xgettext -f- -dsua -osua.pot -LPHP --from-code=UTF-8 --add-comments="I18N:"
